apiVersion: v1
kind: Namespace
metadata:
  name: vti-clothing-shop-monitoring
  labels:
    app.kubernetes.io/name: vti-clothing-shop-monitoring
    app.kubernetes.io/part-of: vti-clothing-shop
    app.kubernetes.io/component: monitoring
