input {
  gelf {
    port => 12201
  }
}

filter {
  mutate {
    add_field => {
      "service.environment" => "docker"
      "service.namespace" => "vti"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "vti-clothing-shop-docker-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
