extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: vti_clothing_shop
  elasticsearch:
    endpoints:
      - http://elasticsearch:9200
    logs_index: vti-clothing-shop-otel-logs
    traces_index: vti-clothing-shop-otel-traces
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  debug:
    verbosity: basic

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - elasticsearch
        - otlp/tempo
        - debug
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - prometheus
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - elasticsearch
        - otlphttp/loki
        - debug
