version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRESQL_DATABASE: clothing_shop
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_EXTERNAL_HOST: database
      POSTGRESQL_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - database
      - redis
    networks:
      - clothing_network

  database:
    image: postgres:alpine
    container_name: clothing_shop_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clothing_shop
    networks:
      - clothing_network

  redis:
    image: redis:alpine
    container_name: clothing_shop_redis
    ports:
      - "6379:6379"
    networks:
      - clothing_network

networks:
  clothing_network:
    driver: bridge