sonar.projectKey=VTI_Clothing_Shop_Server
sonar.projectName=VTI Clothing Shop Server
sonar.sourceEncoding=UTF-8

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.exclusions=target/**,src/main/java/vn/vti/clothing_shop/proto/**
sonar.coverage.exclusions=src/main/java/vn/vti/clothing_shop/ClothingShopApplication.java,src/main/java/vn/vti/clothing_shop/proto/**
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
